### ISSUE TITLE
SendEvent method is not working

### ISSUE THREAD

**Issue by mathrossi** [starmessage/libSoftMeter#12]
SendEvent method is not working for App Delphi, the event does not appear in google analytics, do you have a solution? I'm using Delphi 10.3

**Comment by starmessage** [comment]
Can you share some of your code?
At the free edition, only 3 hits are sent per application run. So if you are already sending other hits and the Event is the 4th, it will be muted.
Please also enable the softmeter log to inspect it yourself and/or send it to me via email.
