### ISSUE TITLE
Test, adapt SoftMeter for sending statistics to a Google Analytics 4 ("G-xxxx") property (not Universal Analytics, "UA-xxxx-y")

### ISSUE THREAD

**Issue by starmessage** [starmessage/libSoftMeter#14]
- Google Analytics introduced in 2020 a new type of tracking property, the "**Google Analytics 4**" property.
- Google Analytics 4 property IDs start with "G-". 
- "Universal Analytics" properties start with a "UA-" prefix. 
On July 1, 2023, Universal Analytics properties will stop processing new hits. See: https://support.google.com/analytics/answer/11583528
- [SoftMeter](https://www.starmessagesoftware.com/softmeter/implementation), up to version 1.4, expects the property ID, as given by the Desktop application, to start with "UA-" and rejects the calls if the ID passed is not like that.
- In an upcoming version of SoftMeter we will add support for Google Analytics 4 properties.
- Google Analytics new properties are created by default as Google Analytics 4 properties.

**Comment by liuying1129** [comment]
Universal Analytics will no longer process new data in standard properties beginning July 1, 2023. Prepare now by setting up and switching over to a Google Analytics 4 property.

Excuse me,  When will it be supported？

**Comment by starmessage** [comment]
We are working on GA4 compatibility, to get it ready in time. There is no ETA yet.

**Comment by ArcticLampyrid** [comment]
Any progress?

**Comment by starmessage** [comment]
This is the 2.0.0 beta version that add support for Google Analytics 4 properties (Measurement ID in the form of G-xxxxxxxx)
[libSoftmeter v2.0.0 beta.zip](https://github.com/starmessage/libSoftMeter/files/10333309/libSoftmeter.v2.0.0.beta.zip)

**Changes needed in your program:**
- before calling the Softmeter start() function, you need to provide the ApiSecret string of your GA4 property.
setOptions("ApiSecret=Your-Api-Secret-As-given-from-GA-administration-config");
- at the call of the start() function, replace your UA-xxxxxxxx-y property ID of your Universal analytics property, with the GA4 measurement id, in the form of G-zzzzzzzzzz

**Missing functionality in this version:**
- Google has not yet announced a date for the public release of the GA4 measurement API. Features are still missing from the API: recording of screen resolution, app name, app version, user language, country, etc.
We are looking to find a workaround for these issues.

**Comment by liuying1129** [comment]
No version 2.0 demo for delphi

**Comment by liuying1129** [comment]
I hope to see the richer documents of version 2.0 as soon as possible

**Comment by starmessage** [comment]
SoftMeter version 2.0.1 was released. https://github.com/starmessage/libSoftMeter/tree/master/bin

**Comment by starmessage** [comment]
Instructions on how to setup your GA4 property to collect application usage data from SoftMeter and the creation of custom dimensions for the SoftMeter PRO metadata.
https://www.starmessagesoftware.com/blog/create-configure-ga4-google-analytics-property-softmeter

**Comment by liuying1129** [comment]
When calling the start() function, if the parameter appVersion is null, version 1.0 is normal, but version 2.0 crashes

**Comment by liuying1129** [comment]
I use delphi to test.
When calling the start() function, if the parameter appVersion is null, version 1.0 is normal, but version 2.0 crashes

**Comment by starmessage** [comment]
Thanks for reporting this. It is fixed and will be available in the next version.
However, the parameters of the start() function should not be NULL. You must pass valid strings.

We are closing this issue as it is specific to the GA4 compatibility. Please open new issues for any bug or improvement that you want to report.
