### ISSUE TITLE
windows delphi 7

### ISSUE THREAD

**Issue by liuying1129** [starmessage/libSoftMeter#15]
![image](https://user-images.githubusercontent.com/12840311/153347951-61f8fac9-9f67-48f9-8985-1c85f6c26ec1.png)

**Comment by starmessage** [comment]
1. for the fallback to http, the reason is that you are running it from Windows XP which does not have the newer SSL protocols
2. For the warning of re-initialization, please check that you call the start() function only once.
3. The warning about the hit is because you are running the [free edition](https://www.starmessagesoftware.com/softmeter/pro) which has limits on how many hits you can send.

**Comment by liuying1129** [comment]
Thanks, I'm Chinese and my English is not good.

The two failed clients are both Windows XP, so the first point should be the correct reason.

How can Windows XP solve this problem?

**Comment by starmessage** [comment]
1. the fallback to http is not a problem. Google Analytics will receive the hit. Do you see pageViews in GA? But before that you must fix the item 2L
2. you must call the start() function only once.

If you post here your source code to show how you call the library, maybe I could help better.

**Comment by liuying1129** [comment]
unit softMeter_globalVar;

interface

uses
  dll_loaderAppTelemetry;

var
  dllSoftMeter: TDllAppTelemetry;

implementation

uses
  dialogs, ShellApi{ShellExecute}; 

var
  userGaveConsent:boolean;

const
  // put here your Google Analytics property ID as given to you 
  // from your Google Analytics account.
  // Or put the Matomo/Piwik tracking ID if you you are using Matomo
  GooglePropertyID =  'UA-207373569-1';
                      
  // put here your application information
  AppName = 'ProYkLis';
  AppVersion = '0.0.7.2';
  AppEdition = 'Enterprise Edition';
  AppLicense = 'Free';
  // if you have a SoftMeter PRO subscription
  PROsubscription = 'subscriptionID=your-subscription-id' + CHR(10) + 'subscriptionType=2';

  {$IFDEF WIN32}
      DLLfilename =  'libSoftMeter.dll';
  {$ENDIF}
  {$IFDEF WIN64}
      DLLfilename =  'libSoftMeter64.dll';
  {$ENDIF}

var
  startResult: boolean;
  logFilename: string;

initialization

  try
    dllSoftMeter := TDllAppTelemetry.Create(DLLfilename);
  Except
    MessageDlg('Error loading '+ DLLfilename,mtError,[mbOK],0);
  end;

  dllSoftMeter.enableLogfile('Delphi demo');
  logFilename := dllSoftMeter.getLogFilename;

  if Length(GooglePropertyID)<10 then
  begin
    MessageDlg('You are running this demo with the propertyID: ' + GooglePropertyID + CHR(10)+CHR(13) +
                'Are you sure this is YOUR Google propertyID?' + CHR(10)+CHR(13) +
                'Go to softMeter_globalVar.pas to review it.' + CHR(10)+CHR(13) +
                'Will not enable telemetry now.',mtWarning,[mbOK],0);
    exit;
  end;

  // set your SoftMeter PRO subscription here, before calling start()
  // dllSoftMeter.setOptions(PChar(PROsubscription));
    
  // make sure you load this variable from the user settings
  userGaveConsent:= true;
  // ToDo: make this a lazy call so that the INI file with the user settings containing the 
  // consent of the user is already loaded somewhere in the program.

  startResult:=false;  
  try
    startResult := dllSoftMeter.start(AppName, AppVersion, AppLicense, AppEdition, GooglePropertyID, userGaveConsent );
  Except
    MessageDlg('Exception while calling dllSoftMeter.start',mtError,[mbOK],0);
  end;
  if not startResult then MessageDlg('dllSoftMeter.start returned false',mtError,[mbOK],0);

  if dllSoftMeter.errorsExist then MessageDlg('Errors in dllSoftMeter:' + dllSoftMeter.getErrorText,mtError,[mbOK],0);

finalization

  try
    dllSoftMeter.stop;
  Except
    MessageDlg('Error calling dllSoftMeter.stop',mtError,[mbOK],0);
  end;

  // during the development (not for release) open the logFile
  ShellExecute( 0 , nil, PChar('notepad'), PChar(logFilename) , nil, 1{SW_SHOWNORMAL} ) ;

//===================================================================
unit Main
//Calling code
  dllSoftMeter.sendPageview(PChar(UTF8Encode(SCSYDW)+'/'+UTF8Encode(operator_id)),'frmMain Show Event');

**Comment by liuying1129** [comment]
It has been changed to 1.4.2, and the prompt is the same

**Comment by liuying1129** [comment]
However, the same code works correctly in win7 and win10

**Comment by starmessage** [comment]
can you please send me by email (sales at starmessage dot info) the two logfiles of running the same EXE program,
a) on winXP and 
b) win7

**Comment by starmessage** [comment]
please use this brand new version 1.4.3 and send back the logs from both winXP and win10.
[libSoftMeter-v1.4.3-beta.zip](https://github.com/starmessage/libSoftMeter/files/8080337/libSoftMeter-v1.4.3-beta.zip)

**Comment by liuying1129** [comment]
Bingo!  Two WinXP clients that failed before have been tested and can be sent to GA normally.
